POST  http://localhost:3000/user


Content-Type: application/json

{
    "firstName": "hacbscsicks cosaif",
    "lastName": "okolnvdv dmkd vjdv d",
    "Email": "Emailom@gmaik.c",
    "Password": "45677",
}

###

GET http://localhost:3000